spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false